export const categories = [
  { name: "Clothing" },
  { name: "Tools" },
  { name: "Skin care" },
  { name: "Home improvement" },
  { name: "Supplements" },
  { name: "Toys & Games" },
  { name: "Uncategorized" },
  { name: "Health & Wellness" },
  { name: "Jewellery" },
  { name: "Food/Groceries" },
  { name: "Cosmetics" },
  { name: "Hair care" },
  { name: "Tea & Coffee" },
  { name: "Baby Products" },
  { name: "Collectibles" },
  { name: "Services" },
  { name: "Watches/Sunglasses/Accessories" },
  { name: "Shoes & Handbags" },
  { name: "Arts & Crafts" },
  { name: "Pet Supplies" },
  { name: "Sexual Wellness" },
  { name: "Computers & Accessories" },
  { name: "Financial Services" },
];